CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    HashedPassword VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL
);
